FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip install uv && \
    uv sync --frozen

COPY src/ src/

EXPOSE 8501

# Set environment variables
ENV PYTHONPATH=/app
ENV UV_SYSTEM_PYTHON=1

# Command to run the Streamlit application
CMD ["uv", "run", "streamlit", "run", "src/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]